-- Localization by @sagevalorant, @ninoleplot, @EDM115
-- Traduction par @sagevalorant, @ninoleplot, @EDM115
return {
	descriptions = {
		Tag = {
			tag_mp_gambling_sandbox = {
				name = "Badge de jeu de hasard",
				text = {
					"{C:green}#1# chance sur #2#{}",
					"que le magasin ait un",
					"{C:red}Joker rare{} gratuit",
				},
			},
			tag_mp_juggle_sandbox = {
				name = "Badge de jongleur",
				text = {
					"Taille de la main {C:attention}+#1#{}",
					"à la prochaine {C:attention}blinde JcJ",
				},
			},
			tag_mp_investment_sandbox = {
				name = "Badge d'investissement",
				text = {
					"Après avoir battu la",
					"blinde Boss, obtenez :",
					"{C:money}$#1#{} + {C:money}$#2#{} par mise initiale",
					"{C:inactive}(Actuellement {C:money}$#3#{C:inactive})",
				},
			},
		},
		Joker = {
			j_broken = {
				name = "CASSÉ",
				text = {
					"Cette carte est cassée, ou n'est",
					"pas implémentée dans une version",
					"actuelle d'un mod que vous utilisez.",
				},
			},
			j_mp_defensive_joker = {
				name = "Joker défensif",
				text = {
					"{C:chips}+#1#{} Jetons par {C:red,E:1}vie{}",
					"de moins que votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:chips}+#2#{C:inactive} Jetons)",
					"{C:inactive}(Dépend de la mise)",
				},
			},
			j_mp_skip_off = {
				name = "Marelle",
				text = {
					"{C:blue}+#1#{} mains et {C:red}+#2#{} Défausses",
					"par {C:attention}blinde{} passée",
					"{C:attention}de plus{} que votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Machine à sous",
				text = {
					"{C:green}#1# chance sur #2#{} d'octroyer",
					"Multi {X:mult,C:white}X#3#{} et {C:money}$#4#{}",
					"{C:green}#5# chance sur #6#{} de donner",
					"{C:money}$#7#{} à votre {X:purple,C:white}Némésis{} en {C:attention}blinde JcJ",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Si vous atteignez une {C:attention}blinde JcJ",
					"avant votre {X:purple,C:white}Némésis{},",
					"crée une carte {C:spectral}Spectrale{} aléatoire",
					"{C:inactive}(Selon la place disponible)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Joker conjoint",
				text = {
					"Pendant une {C:attention}blinde JcJ{}, octroie",
					"Multi {X:mult,C:white}X#1#{} pour chaque {C:blue}main{}",
					"restante de votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Max Multi {X:mult,C:white}X#2#{C:inactive}, actuellement Multi {X:mult,C:white}X#3#{C:inactive})",
				},
			},
			j_mp_penny_pincher = {
				name = "Grippe-sou",
				text = {
					"À la fin d'une manche, obtenez {C:money}$#1#{}",
					"par {C:money}$#2#{} dépensés par votre {X:purple,C:white}Némésis{}",
					"dans le magasin correspondant",
					"de la {C:attention}dernière mise initiale{}",
				},
			},
			j_mp_taxes = {
				name = "Impôts",
				text = {
					"Octroie Multi {C:mult}+#1#{} pour chaque carte",
					"{C:attention}vendue{} par votre {X:purple,C:white}Némésis{}",
					"depuis la dernière {C:attention}blinde JcJ{},",
					"s'actualise quand la {C:attention}blinde JcJ{} est sélectionnée",
					"{C:inactive}(Actuellement Multi {C:mult}+#2#{C:inactive})",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"À la fin de la prochaine {C:attention}blinde JcJ{},",
					"consomme ce Joker et octroie",
					"durant la mise initiale",
					"{C:red}+#1#{} défausse pour vous et",
					"{C:red}+#2#{} défausse pour votre {X:purple,C:white}Némésis{}",
				},
			},
			j_mp_pacifist = {
				name = "Pacifiste",
				text = {
					"Octroie Multi {X:mult,C:white}X#1#{}",
					"{C:attention}sauf{} pendant les {C:attention}blindes JcJ{}",
				},
			},
			j_mp_hanging_chad = {
				name = "Carte de vote",
				text = {
					"Déclenche {C:attention}#1#{} fois supplémentaire",
					"la {C:attention}première{} et {C:attention}seconde{}",
					"carte jouée marquant des points",
				},
			},
			j_mp_bloodstone = {
				name = "Pierre de sang",
				text = {
					"{C:green}#1# chance sur #2#{}",
					"pour que les cartes jouées avec une",
					"couleur {C:hearts}coeur{} octroient",
					"Multi {X:mult,C:white} X#3# {} en marquant des points",
				},
			},
			j_mp_magnet_sandbox = {
				name = "Aimant",
				text = {
					"Après {C:attention}#1#{} manches,",
					"vendez cette carte pour {C:attention}copier{}",
					"le {C:attention}Joker{} à la plus haute ",
					"valeur de vente de votre {X:purple,C:white}Némésis{}",
					"Polarité inversée après {C:attention}#3#{} manches",
					"DEVIENT UN BOUT DE MÉTAL INUTILE !!!!",
					"{C:inactive}(Actuellement {C:attention}#2#{C:inactive}/#1# manches)",
				},
			},
			j_mp_cloud_9_sandbox = {
				name = "Neuvième ciel",
				text = {
					"FERMIER DE NOMBRES MONOCULTURE",
					"convertissant votre DECK VARIÉ en une",
					"PLANTATION RENTABLE DE NEUF !!!!",
					"{C:inactive}({C:green}#1# chance sur #2#{}{C:inactive}, actuellement {C:money}$#3#{}{C:inactive})",
				},
			},
			j_mp_lucky_cat_sandbox = {
				name = "Porte-bonheur",
				text = {
					"OPÉRATEUR DE PIPELINE FORTUNE-VERS-FRAGILITÉ",
					"les porte-bonheur deviennent des CHATS DE VERRE",
					"avec un POUVOIR EXPONENTIEL !!!!",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#2# {C:inactive})",
				},
			},
			j_mp_constellation_sandbox = {
				name = "Constellation",
				text = {
					"Anxiété liée à l'entretien des planètes",
					"IL FAUT NOURRIR LE TAMAGOCHI",
					"sinon il DISPARAÎT !!!!",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#1# {C:inactive})",
				},
			},
			j_mp_bloodstone_sandbox = {
				name = "Pierre de sang",
				text = {
					"{V:1}SYNDROME DE RÉGRESSION DES MISES À JOUR",
					"retour au TRAUMATISME DU JOUR DE LANCEMENT",
					"pour des PICS DE PUISSANCE {X:mult,C:white}X#3#{} NOSTALGIQUES !!!!",
					"{C:inactive}({C:green}#1# chance sur #2#{}{C:inactive})",
				},
			},
			j_mp_juggler_sandbox = {
				name = "Jongleur",
				text = {
					"PERFECTIONNISTE DE LA TAILLE DES MAINS",
					"qui doit garder TOUTES LES CARTES",
					"en l'air EN PERMANENCE !!!!",
					"{C:inactive}(Actuellement {C:attention}+#1#{C:inactive} à la taille de la main)",
				},
			},
			j_mp_mail_sandbox = {
				name = "Remise par courrier",
				text = {
					"Obtenez {C:money}$#1#{} pour chaque",
					"{C:attention}#2#{} défaussé",
					"{s:0.8}La valeur ne change jamais",
				},
			},
			j_mp_hit_the_road_sandbox = {
				name = "Prendre la route",
				text = {
					"Ce Joker octroie Multi {X:mult,C:white}X0.75{}",
					"pour chaque {C:attention}Valet{} défaussé",
					"Les Valets défaussés sont {C:attention}détruits{}",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#2# {C:inactive})",
				},
			},
			j_mp_misprint_sandbox = {
				name = "Erreur d'impression",
				text = {
					"Multi {V:1}#1#{}",
					"{C:attention}Valeur révélée à l'achat{}",
					"{C:green}Les erreurs d'impression s'accumulent{}",
				},
			},
			j_mp_castle_sandbox = {
				name = "Château",
				text = {
					"Ce Joker octroie {C:chips}#3{} Jetons",
					"par carte {V:1}#1#{} défaussée",
					"La couleur est bloquée à l'achat",
					"{C:inactive}(Actuellement {C:chips}+#2#{C:inactive} Jetons)",
				},
			},
			j_mp_runner_sandbox = {
				name = "Coureur",
				text = {
					"SUPRÉMATISTE DES CARTES SÉQUENTIELLES",
					"qui considère que TOUTES les autres",
					"MAINS DE POKER sont INFÉRIEURES !!!!",
					"{C:inactive}(Actuellement {C:chips}+#1#{C:inactive})",
				},
			},
			j_mp_order_sandbox = {
				name = "L'Ordre",
				text = {
					"Multi {X:mult,C:white}X3{} si la main jouée contient une {C:attention}Suite{}",
					"Octroie Multi {X:mult,C:white}X#1#{} pour chaque {C:attention}Suite{} consécutive jouée",
					"Se réinitialise quand une autre main est jouée",
					"{C:inactive}(Actuellement Multi {X:mult,C:white}X#2#{C:inactive})",
				},
			},
			j_mp_photograph_sandbox = {
				name = "Photographie",
				text = {
					"PHOTOGRAPHE SPÉCIALISÉ DANS LES CLICHÉS UNIQUES",
					"qui octroie UNE SEULE PHOTO PARFAITE PAR MAIN !!!!",
				},
			},
			j_mp_ride_the_bus_sandbox = {
				name = "Tour en bus",
				text = {
					"PROGRAMME DE SOBRIÉTÉ DES CARTES FIGURES",
					"UNE SEULE CARTE FIGURE et vous êtes",
					"VIRÉS DU BUS !!!!",
					"{C:inactive}(Actuellement Multi {C:mult}+#1#{C:inactive})",
				},
			},
			j_mp_loyalty_card_sandbox = {
				name = "Carte de fidélité",
				text = {
					"Multi {X:mult,C:white}X6{} toutes les {C:attention}#3#{}",
					"mains {C:attention}#1#{} jouées",
					"{C:inactive}(#2#/#3#)",
				},
			},
			j_mp_faceless_sandbox = {
				name = "Joker sans visage",
				text = {
					"SOMMELIER DE RÉFÉRENCE POUR CARTES FIGURES",
					"qui organise des DÉGUSTATIONS",
					"ARTISANALES DE TROIS VARIÉTÉS",
					"pour des EXPÉRIENCES DE DÉFAUSSE D'EXCEPTION !!!!",
				},
			},
			j_mp_square_sandbox = {
				name = "Joker carré",
				text = {
					"Ce Joker octroie {C:chips}+#2#{} Jetons",
					"si la main jouée possède",
					"exactement {C:attention}4{} cartes",
					"{C:attention}S'applique uniquement pour les mains de 4 cartes{}",
					"{C:inactive}(Actuellement {C:chips}+#1#{C:inactive} Jetons)",
				},
			},
			j_mp_throwback_sandbox = {
				name = "Rappel",
				text = {
					"Multi de base {X:mult,C:white}X#2#{} pour chaque",
					"{C:attention}blinde{} passée durant cette partie",
					"Multi {X:mult,C:white}X#3#{} à la prochaine blinde après l'avoir passée",
					"Perd Multi {X:mult,C:white}X#4#{} lorsque la blinde n'est pas passée",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#1# {C:inactive})",
				},
			},
			j_mp_vampire_sandbox = {
				name = "Vampire",
				text = {
					"Ce joker octroie Multi {X:mult,C:white}X#1#{} par",
					"{C:attention}carte améliorée{} jouée marquant des points",
					"Elles deviennent ensuite des {C:attention}cartes Pierre{}",
					"Les cartes Pierre jouées octroient {C:money}$#3#{}",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#2# {C:inactive})",
				},
			},
			j_mp_baseball_sandbox = {
				name = "Carte de baseball",
				text = {
					"Les Jokers {C:green}peu communs{}",
					"octroient chacun",
					"Multi {X:mult,C:white}X#1#{}",
				},
			},
			j_mp_steel_joker_sandbox = {
				name = "Joker d'acier",
				text = {
					"{C:attention}Déclenche à nouveau{}",
					"les cartes Acier jouées",
				},
			},
			j_mp_satellite_sandbox = {
				name = "Satellite",
				text = {
					"anxiété liée à la dégradation chronique des satellites",
					"L'INFRASTRUCTURE SE DÉGRADE LENTEMENT",
					"SANS AMÉLIORATIONS PLANÉTAIRES CONSTANTES !!!!",
					"{C:inactive}(Actuellement {C:money}$#1#{C:inactive})",
				},
			},
			j_mp_idol_sandbox_bw = {
				name = "L'idole fanatique",
				text = {
					"Chaque {C:attention}#1#{} joué",
					"octroie Multi {X:mult,C:white}X#2#{}",
					"en marquant des points",
					"{s:0.8}La carte change à chaque manche",
				},
			},
			j_mp_idol_sandbox_color = {
				name = "L'idole de la colère",
				text = {
					"AUTOCUISEUR À PRESSION DÉVOTIONNEL",
					"accumulant de la VAPEUR pour {C:attention}#1#{} de {V:1}#3#{}",
					"jusqu'à la LIBÉRATION EXPLOSIVE !!!!",
					"{C:inactive}(Actuellement Multi {X:mult,C:white} X#2# {C:inactive})",
				},
			},
			j_mp_idol_sandbox_fantom = {
				name = "Le meta-idole",
				text = {
					"La carte la plus commune octroie",
					"Multi {X:mult,C:white}X#3#{} en marquant des points",
					"({X:mult,C:white}+X#4#{} par copie dans le jeu)",
					"{C:inactive}(Actuellement {C:attention}#1#{} de {V:1}#2#{})",
				},
			},
			j_mp_error_sandbox = {
				name = "????",
				text = {
					-- "PRÉVISUALISATION DÉSACTIVÉE",
					"{X:purple,C:white,s:0.85}quelque chose{} {X:purple,C:white,s:0.85}ne va pas",
					-- "PRÉVISUALISATION DÉSACTIVÉE",
					-- "PRÉVISUALISATION DÉSACTIVÉE",
					-- "{C:inactive}(Actuellement {C:money}$7{C:inactive})",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Astéroïde",
				text = {
					"Retire #1# niveau à",
					"la {C:legendary,E:1}main de poker{}",
					"la plus améliorée de votre {X:purple,C:white}Némésis{}",
					"au début de la {C:attention}blinde JcJ{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Votre Némésis",
				text = {
					"Jouez contre un autre joueur,",
					"le plus haut score l'emporte",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantôme",
				text = {
					"{C:attention}Éternel{} et {C:dark_edition}Négatif{}",
					"Créé et détruit par votre {X:purple,C:white}Némésis{}",
				},
			},
		},
		Enhanced = {
			m_mp_glass = {
				name = "Carte Verre",
				text = {
					"Multi {X:mult,C:white} X#1# {}",
					"{C:green}#2# chance sur #3#{} de",
					"détruire la carte",
				},
			},
		},
		Back = {
			b_mp_cocktail = {
				name = "Jeu cocktail",
				text = {
					"Copie tous les effets",
					"de {C:attention}3{} autres jeux",
					"au hasard",
				},
			},
			b_mp_gradient = {
				name = "Jeu dégradé",
				text = {
					"Les cartes sont aussi considérées",
					"un rang {C:attention}supérieur{} ou {C:attention}inférieur",
					"pour tous les effets des {C:attention}Jokers{}",
				},
			},
			b_mp_heidelberg = {
				name = "Jeu Heidelberg",
				text = {
					"Crée une copie {C:dark_edition}Négative{}",
					"d'{C:attention}1 consommable{} aléatoire",
					"en votre possession",
					"à la fin du magasin",
				},
			},
			b_mp_indigo = {
				name = "Jeu indigo",
				text = {
					"Choisissez {C:attention}1{} carte supplémentaire",
					"dans tous les Paquets Booster",
					"(ils {C:attention}ne peuvent pas être passés{})",
				},
			},
			b_mp_oracle = {
				name = "Jeu oracle",
				text = {
					"Démarre la partie avec",
					"{C:spectral,T:c_medium}Médium et {C:attention,T:v_clearance_sale}Déstockage",
					"L'argent est limité à {C:money}$50{}",
					"+ {C:attention}la limite actuelle des intérêts{}",
				},
			},
			b_mp_orange = {
				name = "Jeu orange",
				text = {
					"Démarre la partie avec un",
					"{C:attention,T:p_mp_standard_giga}Paquet Giga Standard{}, et",
					"{C:attention}2{} copies du {C:tarot,T:c_hanged_man}Pendu",
				},
			},
			b_mp_violet = {
				name = "Jeu violet",
				text = {
					"{C:attention}+1{} Coupon dans le magasin",
					"Pendant la mise initiale {C:attention}1{},",
					"les coupons sont à {C:attention}-50%{}",
				},
			},
			b_mp_white = {
				name = "Jeu blanc",
				text = {
					"Consultez le jeu actuel de votre",
					"{X:purple,C:white}Némésis{} et ses Jokers",
					"{C:inactive}(S'actualise à la blinde JcJ){}",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Némésis",
				text = {
					"{X:purple,C:white}#1#{}",
					"Votre seul et unique Némésis",
				},
			},
			p_mp_standard_giga = {
				name = "Paquet Giga-Standard",
				text = {
					"Choisissez {C:attention}#1#{} parmi",
					"{C:attention}#2#{C:attention} cartes à jouer{} à",
					"ajouter à votre jeu",
					"{C:attention}Ne peut pas être passé{}",
				},
			},
			mp_transmutations = {
				name = "Transformations",
				text = {
					"{C:purple,s:1.1}Se transformera en :",
				},
			},
		},
		Stake = {
			stake_mp_planet = {
				name = "Mise planète",
				text = {
					"Applique les effets de la {C:black}Mise noire{}, plus :",
					"Les magasins peuvent posséder des Jokers {C:money}périssables{}",
					"{C:inactive,s:0.8}(Affaiblis après 5 manches)",
					"Le score requis augmente plus",
					"rapidement pour chaque {C:attention}mise initiale",
				},
			},
			stake_mp_spectral = {
				name = "Mise spectrale",
				text = {
					"Applique les effets de la {C:planet}Mise planète{}, plus :",
					"Les magasins peuvent posséder des Jokers {C:money}location{}",
					"Le score requis augmente plus",
					"rapidement pour chaque {C:attention}mise initiale",
				},
			},
			stake_mp_spectralplus = {
				name = "Mise spectrale+",
				text = {
					"Applique les effets de la  {C:planet}Mise spectrale{}, plus :",
					"Le score requis augmente encore plus",
					"rapidement pour chaque {C:attention}mise initiale",
				},
			},
		},
		Spectral = {
			c_mp_ouija_sandbox = {
				name = "Ouija",
				text = {
					"Détruit {C:attention}#1#{} cartes aléatoires,",
					"puis convertit toutes les cartes",
					"restantes en une unique {C:attention}valeur{} aléatoire",
				},
			},
			c_mp_ectoplasm_sandbox = {
				name = "Ectoplasme",
				text = {
					"Ajoute {C:dark_edition}Négatif{}",
					"à un {C:attention}Joker aléatoire{},",
					"applique aléatoirement l'un des effets suivants :",
					"{C:red}-1{} main, {C:red}-1{} défausse ou taille de la main {C:red}-1{}",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Fantôme",
		},
		challenge_names = {
			c_mp_standard = "Standard",
			c_mp_sandbox = "Bac à sable",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Tournoi",
			c_mp_weekly = "Hebdo",
			c_mp_vanilla = "Vanilla",
		},
		dictionary = {
			b_singleplayer = "Solo",
			b_join_lobby = "Rejoindre un salon",
			b_join_lobby_clipboard = "Rejoindre depuis le presse-papiers",
			b_return_lobby = "Retourner au salon",
			b_reconnect = "Se reconnecter",
			b_create_lobby = "Créer un salon",
			b_start_lobby = "Lancer la partie",
			b_ready = "Prêt",
			b_unready = "Pas prêt",
			b_leave_lobby = "Quitter le salon",
			b_mp_discord = "Serveur Discord Balatro Multijoueur",
			b_start = "COMMENCER",
			b_wait_for_host_start = { "EN ATTENTE DE", "L'HÔTE POUR COMMENCER" },
			b_wait_for_players = { "EN ATTENTE DES", "JOUEURS" },
			b_wait_for_guest_ready = { "EN ATTENTE QUE LES", "INVITÉS SOIENT PRÊTS" },
			b_lobby_options = "OPTIONS DU SALON",
			b_copy_clipboard = "Copier vers le presse-papiers",
			b_view_code = "VOIR LE CODE",
			b_copy_code = "COPIER LE CODE",
			b_leave = "PARTIR",
			b_opts_cb_money = "Gagner des $ lors de la perte d'une vie",
			b_opts_no_gold_on_loss = "Ne pas obtenir les récompenses de la blinde lors d'une défaite",
			b_opts_death_on_loss = "Perdre une vie après une défaite contre une blinde non-JcJ",
			b_opts_start_antes = "Mises initiales de départ",
			b_opts_diff_seeds = "Seeds différentes pour les joueurs",
			b_opts_lives = "Vies",
			b_opts_multiplayer_jokers = "Activer les cartes multijoueur",
			b_opts_player_diff_deck = "Les joueurs peuvent avoir des decks différents",
			b_opts_normal_bosses = "Activer les effets des blindes Boss",
			b_opts_timer = "Activer le minuteur",
			b_opts_disable_preview = "Désactiver l'aperçu du score",
			b_opts_the_order = "Activer The Order",
			b_opts_legacy_smallworld = "Anciens mécanismes de Petit Monde",
			b_reset = "Réinitialiser",
			b_set_custom_seed = "Seed personnalisée",
			b_mp_kofi_button = "Me soutenir sur Ko-fi",
			b_unstuck = "Se décoincer",
			b_unstuck_blind = "Coincé en dehors du JcJ",
			b_misprint_display = "Afficher la prochaine carte du jeu",
			b_players = "Joueurs",
			b_lobby_info = "Infos du salon",
			b_continue_singleplayer = "Continuer en solo",
			b_the_order_integration = "Activer l'intégration de The Order",
			b_preview_integration = "Activer l'aperçu du score",
			b_view_nemesis_deck = "Voir les decks",
			b_toggle_jokers = "Activer / Désactiver les Jokers",
			b_skip_tutorial = "Passer le tutoriel",
			k_yes = "Oui",
			k_no = "Non",
			k_are_you_sure = "Êtes-vous sûr ?",
			k_has_multiplayer_content = "Contient du contenu multijoueur",
			k_forces_lobby_options = "Force les options du salon",
			k_forces_gamemode = "Force le mode de jeu",
			k_values_are_modifiable = "* Les valeurs sont modifiables",
			k_rulesets = "Règles",
			k_gamemodes = "Modes de jeu",
			k_competitive = "Compétitif",
			k_other = "Autre",
			k_battle = "Bataille",
			k_challenge = "Challenge",
			k_info = "Info",
			k_continue_singleplayer_tooltip = "Votre partie en solo sera écrasée",
			k_enemy_score = "Score ennemi actuel",
			k_enemy_hands = "Mains adverses restantes : ",
			k_coming_soon = "Bientôt !",
			k_wait_enemy = "En attente que l'adversaire termine...",
			k_wait_enemy_reach_this_blind = "En attente que l'adversaire atteigne cette blinde...",
			k_lives = "Vies",
			k_lost_life = "A perdu une vie",
			k_total_lives_lost = " Total de vies perdues ($4 chacune)",
			k_comeback_money_sandbox = " Compensation financière ($3 × mise initiale complétée)",
			k_attrition_name = "Érosion",
			k_enter_lobby_code = "Entrer le code du salon",
			k_paste = "Coller depuis le presse-papiers",
			k_username = "Pseudo :",
			k_enter_username = "Entrer un pseudo",
			k_customize_preview = "Personnaliser le texte de l'aperçu :",
			k_join_discord = "Rejoindre le ",
			k_discord_msg = "Vous pourrez y signaler des bugs et trouver des joueurs avec qui jouer",
			k_enter_to_save = "Appuyez sur Entrée pour sauvegarder",
			k_in_lobby = "Dans le salon",
			k_connected = "Connecté aux services",
			k_warn_service = "ATTENTION : Impossible de trouver le service multijoueur",
			k_set_name = "Entrez votre pseudo dans le menu ! (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "Des joueurs n'ont pas les même mods / versions de mods ! Cela peut causer des problèmes !",
			k_steamodded_warning = "Des joueurs possèdent différentes versions de Steamodded installées. Cela peut causer des seeds différentes.",
			k_warning_unlock_profile = "Le profil actuel n'a pas tout le contenu débloqué. Si cette partie est classée / un tournoi, veuillez créer un nouveau profil et cliquer sur tout débloquer dans les paramètres du profil.",
			k_warning_nemesis_unlock = "Votre adversaire joue sur un profil qui n'a pas tout débloqué. Indiquez-lui d'appuyer sur tout débloquer dans les paramètres de son profil.",
			k_warning_no_order = "Un joueur a activé l'intégration de The Order mais l'autre non. Les seeds seront peut-être différentes.",
			k_warning_cheating1 = "Si vous lisez ceci, il se peut que votre adversaire triche.",
			k_warning_cheating2 = "Si cette partie est classée, envoyez le message '%s' et ouvrez un ticket de support dans #support.",
			k_warning_banned_mods = "Un ou plusieurs joueurs ont des mods bannis installés. Ces mods ne sont pas autorisés en partie classée.",
			k_message1 = "Attends, ma mère a fait des mini-pizzas",
			k_message2 = "Bouge pas, faut que j’aille sortir le rôti du four",
			k_message3 = "Une seconde, c’est ma mère qui m’appelle",
			k_message4 = "Je reviens, mon chat est en feu",
			k_message5 = "Attends, j'ai oublié de fermer le gaz",
			k_message6 = "Attends, mon caillou de compagnie a pris la fuite",
			k_message7 = "Deux secondes, mes plantes réclament de l'eau",
			k_message8 = "Je reviens, mes chaussettes complotent contre moi",
			k_message9 = "Désolé, mon Wi-Fi traverse une crise existentielle",
			k_lobby_options = "Options du salon",
			k_connect_player = "Joueurs connectés :",
			k_opts_only_host = "Seul l'hôte du salon peut changer ces options",
			k_lobby_general = "Général",
			k_lobby_gameplay = "Jeu",
			k_lobby_modifiers = "Modifications",
			k_lobby_advanced = "Avancé",
			k_opts_pvp_start_round = "Le JcJ commence à la mise initiale",
			k_opts_pvp_timer = "Minuteur",
			k_opts_showdown_starting_antes = "L'affrontement commence à la mise initiale",
			k_opts_pvp_timer_increment = "Incrémentation du minuteur",
			k_opts_pvp_countdown_seconds = "Compte à rebours JcJ en secondes",
			k_bl_life = "Vie",
			k_bl_or = "ou",
			k_bl_death = "Mort",
			k_bl_mostchips = "Le plus de Jetons l'emporte",
			k_current_seed = "Seed actuelle : ",
			k_random = "Aléatoire",
			k_standard = "Standard",
			k_sandbox = "Bac à sable",
			k_sandbox_description = "Trois idoles jalouses s'affrontent désormais pour votre partie !\nDouze jokers remplacés par des troubles de la personnalité.\nLe Ouija détruit des cartes au lieu de la taille de la main.\nAperçu du score désactivé. Pas d'organigrammes.\nTout ce que vous saviez d'autre ? Allez voir le wiki !",
			k_vanilla = "Vanilla",
			k_vanilla_description = "Ce mode de jeu supprime tout le contenu multijoueur,\nvous permettant de jouer comme prévu à l'origine.\n\nIl conserve les fonctionnalités multijoueur, comme le minuteur.\n\n(Désactivable dans les options du salon)",
			k_blitz = "Standard",
			k_blitz_description = "Ce mode de jeu inclut des cartes et fonctionnalités qui encouragent\nun jeu rapide et une gestion efficace du temps.\n\nCertaines cartes ont été rééquilibrées pour mieux s'adapter au mode multijoueur :\n- Carte de vote est retravaillée\n- La Justice est supprimée\n- Le Verre est retravaillé\n\n(Voir les onglets bans et refontes pour plus d'info)",
			k_traditional = "Traditionnel",
			k_traditional_description = "Ce mode de jeu supprime les aspects du multijoueur qui utilisent le temps comme ressource.\n\nIl vous permet de profiter du contenu multijoueur\ntout en conservant une approche méthodique du jeu.\n\nCertaines cartes ont été rééquilibrées pour mieux s'adapter au mode multijoueur :\n- Carte de vote est retravaillée\n- La Justice est supprimée\n- Le Verre est retravaillé\n\n(Voir les onglets bans et refontes pour plus d'info)",
			k_majorleague = "Ligue majeure",
			k_majorleague_description = "Voici le règlement officiel de la ligue majeure de Balatro.\n\nCe mode de jeu est identique au Vanilla à quelques exceptions près :\n- L'intégration de The Order est désactivée\n- Le minuteur est réglé sur 180 secondes\n- La première fois que le minuteur atteint 0 secondes vous ne perdez pas de vie",
			k_minorleague = "Ligue mineure",
			k_minorleague_description = "Voici le règlement officiel de la ligue mineure de Balatro.\n\nCe mode de jeu est identique au Vanilla à quelques exceptions près :\n- L'intégration de The Order est activée\n- Le minuteur est réglé sur 180 secondes\n- La première fois que le minuteur atteint 0 secondes vous ne perdez pas de vie",
			k_ranked = "Classé",
			k_ranked_description = "Voici le règlement officiel pour jouer à Balatro Multijoueur classé.\n\nCe mode de jeu est identique au Standard à quelques exceptions près :\n- L'intégration de The Order est activée\n- Vous devez être sur la version recommandée de Steamodded",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Des règles hebdomadaires écrites par @dr_monty_the_snek sur le serveur discord\nqui ont été ajoutées au mod de façon permanente.\n\nCe mode de jeu bannit 48 jokers, consommables, badges, ...",
			k_attrition = "Érosion",
			k_attrition_description = "Après la première mise initiale, toutes les blindes Boss sont JcJ. Pas le temps de se préparer. Ce mode force à être prêt au combat dès le début.",
			k_showdown = "Confrontation",
			k_showdown_description = "Après les 2 premières mises initiales, toutes les blindes sont JcJ. Ce mode laisse le temps de se préparer avant le combat.",
			k_survival = "Survie",
			k_survival_description = "Pas de blindes JcJ, le joueur allant le plus loin dans la partie gagne. Ce mode permet de tester vos capacités à accumuler progressivement les meilleures mains dans le jeu Vanilla.",
			k_weekly = "Hebdo",
			k_weekly_description = "Des règles spéciales qui changent toutes les une ou deux semaines. Essayez par vous-même ! Actuellement : ",
			k_smallworld = "Petit monde",
			k_smallworld_description = "Un mode de jeu très expérimental, où les 3/4 du jeu sont bannis aléatoirement sans raison particulière",
			k_destabilized = "Déstabilisé",
			k_oops_ex = "Oups !",
			k_asteroids = "Astéroïdes",
			k_amount_short = "Qté",
			k_filed_ex = "C'est envoyé !",
			k_timer = "Minuteur",
			k_mods_list = "Liste des mods",
			k_enemy_jokers = "Jokers adverses",
			k_your_jokers = "Vos Jokers",
			k_nemesis_deck = "Jeu adverse",
			k_your_deck = "Votre jeu",
			k_the_order_credit = "*Crédit à @MathIsFun_",
			k_the_order_integration_desc = "La création de carte sera modifiée pour ne pas être basée sur la mise initiale et pour utiliser un seul pool pour chaque type / rareté",
			k_preview_credit = "*Crédit à @Fantom, @Divvy",
			k_preview_integration_desc = "Active l'aperçu du score avant de jouer une main",
			k_requires_restart = "*Nécessite un redémarrage pour s'appliquer",
			k_cocktail_select = "Sélectionnez les jeux à inclure",
			k_cocktail_shiftclick = "Maj + clic pour rendre Brillant, les jeux Brillants seront toujours sélectionnés",
			k_cocktail_rightclick = "Clic droit pour tout sélectionner",
			k_bans = "Bans",
			k_reworks = "Refontes",
			k_edit = "Modifier",
			k_ruleset_disabled_the_order_required = "The Order est requis",
			k_ruleset_disabled_the_order_banned = "The Order est banni",
			k_ruleset_not_found = "Règles inconnues",
			k_tutorial_not_complete = "Vous devez terminer le tutoriel avant de pouvoir jouer en multijoueur",
			k_created_by = "Créé par",
			k_major_contributors = "Contributions majeures par",
			ml_enemy_loc = { "Position", "ennemie" },
			ml_mp_kofi_message = {
				"Ce mod et ce serveur de jeu sont",
				"développés et maintenus par ",
				"une seule personne, si",
				"vous l'aimez, n'hésitez pas à",
			},
			ml_lobby_info = { "Infos", "salon" },
			loc_ready = "Prêt pour le JcJ",
			loc_selecting = "Sélectionne une blinde",
			loc_shop = "Dans le magasin",
			loc_playing = "Joue ",
		},
		v_dictionary = {
			a_mp_art = { "Art : #1#" },
			a_mp_code = { "Code : #1#" },
			a_mp_idea = { "Idée : #1#" },
			a_mp_skips_ahead = { "#1# blindes passées d'avance" },
			a_mp_skips_behind = { "#1# blindes passées de moins" },
			a_mp_skips_tied = { "à égalité" },
			k_banned_objs = "#1# bannis",
			k_no_banned_objs = "Pas de #1# bannis",
			k_reworked_objs = "#1# modifiés",
			k_no_reworked_objs = "Pas de #1# modifiés ",
			k_ruleset_disabled_smods_version = "SMODS version #1# requise",
			k_failed_to_join_lobby = "Impossible de rejoindre le salon : #1#",
			k_ante_number = "Mise initiale #1#",
			k_ante_range = "Mise initiale #1#-#2#", -- Par exemple, "Mise initiale 1-2"
			k_ante_min = "Mise initiale #1#+", -- Par exemple, "Mise initiale 2+"
			k_credits_list = "#1# et bien plus !", -- #1# est remplacé par une liste de noms
		},
		v_text = {
			ch_c_hanging_chad_rework = { "{C:attention}Carte de vote{} est {C:dark_edition}modifiée" },
			ch_c_glass_cards_rework = { "{C:attention}Les cartes Verre{} sont {C:dark_edition}modifiées" },
			ch_c_mp_score_instability = { "Le score déséquilibré l'est {C:purple}encore plus{} :" },
			ch_c_mp_score_instability_EXAMPLE = {
				"  {C:inactive}(ex : {C:chips}30{C:inactive}x{C:mult}24{C:inactive} -> {C:chips}36{C:inactive}x{C:mult}18{C:inactive})",
			},
			ch_c_mp_score_instability_LOC1 = { "  {C:inactive}Minimum de {C:attention}1 {C:mult}Multi" },
			ch_c_mp_score_instability_LOC2 = { "  {C:inactive}Minimum de {C:attention}0 {C:chips}Jetons" },
			ch_c_mp_ante_scaling = { "Taille de la blinde de base {C:red}X#1#{}" },
			ch_c_mp_no_shop_planets = {
				"Les cartes {C:planet}planète{} n'apparaissent plus dans le {C:attention}magasin",
			},
			ch_c_mp_only_medium = { "Toutes les cartes {C:spectral}spectrales{} sont des {C:spectral}Médium{}" },
			ch_c_mp_only_purple_seals = { "Tous les {C:attention}sceaux{} sont des {C:purple}sceaux violets{}" },
			ch_c_mp_sibyl_CREDITS = { "{C:inactive}(Art par {C:attention}Ganpan14O{C:inactive})" },
			ch_c_mp_polymorph_spam = {
				"En sélectionnant la blinde, tous les {C:attention}Jokers{} et",
			},
			ch_c_mp_polymorph_spam_EXTENDED1 = {
				"{C:attention}consommables{} possédés sont transformés en la {C:attention}N{}ième carte suivante",
			},
			ch_c_mp_polymorph_spam_EXTENDED2 = {
				"dans leur collection, où {C:attention}N{} est leur position actuelle",
			},
		},
		challenge_names = {
			c_mp_misprint_deck = "Deck erreur d'impression",
			c_mp_legendaries = "Légendaires",
			c_mp_psychosis = "Psychose",
			c_mp_scratch = "De zéro",
			c_mp_twin_towers = "Tours jumelles",
			c_mp_in_the_red = "Dans le rouge",
			c_mp_paper_money = "Billets de banque",
			c_mp_high_hand = "Grande main",
			c_mp_chore_list = "Liste des tâches",
			c_mp_oops_all_jokers = "Que des Jokers !",
			c_mp_divination = "Divination",
			c_mp_skip_off = "La marelle",
			c_mp_lets_go_gambling = "Le casino",
			c_mp_speed = "Vitesse",
			c_mp_balancing_act = "Exercice d'équilibriste",
			c_mp_salvaged_sibyl = "Sibylle sauvée",
			c_mp_polymorph_spam = "Spam polymorphe",
		},
	},
}
