-- Localization by CUexter on GitHub
return {
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "你的對手",
				text = {
					"面對其他玩家，",
					"得分最多的人贏",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "多人遊戲",
		},
		dictionary = {
			-- Legacy keys kept for compatibility
			singleplayer = "單人模式",
			join_lobby = "加入大廳",
			return_lobby = "返回大廳",
			reconnect = "重新連線",
			desc = "讓你與其他玩家對戰",
			create_lobby = "建立大廳",
			start_lobby = "開始大廳",
			enemy_score = "目前對手分數",
			enemy_hands = "對手剩餘手數",
			coming_soon = "即將推出",
			ready = "準備",
			unready = "取消準備",
			wait_enemy = "等待對手完成...",
			lives = "生命",
			leave_lobby = "離開大廳",
			lost_life = "失去一條命",
			failed = "失敗",
			defeat_enemy = "擊敗對手",
			total_lives_lost = "總共失去的生命（每條命 $4）",
			attrition_name = "消耗戰",
			attrition_desc = "每個 Boss 回合都是玩家之間的比賽，分數較低的玩家會失去一條命",
			draft_name = "選拔戰",
			draft_desc = "雙方玩家會玩三次正常底注，然後進入一次對決，該回合分數較低者會失去一條命",
			royale_name = "大亂鬥",
			royale_desc = "類似消耗戰，但有八位玩家且每人只有一條命",
			vanilla_plus_name = "經典+",
			vp_desc = "第一個輸的人就輸，沒有 PvP 盲注",
			enter_lobby_code = "輸入大廳密碼",
			join_clip = "從剪貼簿貼上",
			username = "使用者名稱：",
			enter_username = "輸入使用者名稱",
			join_discord = "加入",
			discord_name = "Balatro 多人模式 Discord",
			discord_msg = "你可以在那裡回報錯誤並找到玩家一起遊玩",
			enter_to_save = "按 Enter 儲存",
			in_lobby = "在大廳中",
			connected = "已連線到服務",
			warn_service = "警告：找不到多人連線服務",
			set_name = "可在主選單設定名稱（Mods > Multiplayer）",
			start = "開始",
			wait_for = "等待",
			host_start = "房主開始",
			players = "玩家",
			lobby_options = "大廳設定",
			lobby_options_cap = "大廳設定",
			copy_clipboard = "複製到剪貼簿",
			connect_player = "已連線玩家：",
			view_code = "查看代碼",
			copy_code = "複製代碼",
			leave = "離開",
			opts_only_host = "只有房主可以更改這些設定",
			opts_cb_money = "失去生命時給予補助金",
			opts_no_gold_on_loss = "回合失敗時不獲得盲注獎勵",
			opts_death_on_loss = "在非 PvP 回合失敗時失去一條命",
			opts_start_antes = "起始底注",
			opts_diff_seeds = "玩家使用不同種子",
			opts_lives = "生命數",
			opts_gm = "模式修改效果",
			bl_or = "或",
			bl_life = "生",
			bl_death = "死",
			lobby = "大廳",
			return_to = "返回",

			-- Current key format used by the main UI
			b_singleplayer = "單人模式",
			b_sp_with_ruleset = "練習模式",
			b_join_lobby = "加入大廳",
			b_join_lobby_clipboard = "從剪貼簿加入",
			b_return_lobby = "返回大廳",
			b_reconnect = "重新連線",
			b_create_lobby = "建立大廳",
			b_start_lobby = "開始大廳",
			b_ready = "準備",
			b_unready = "取消準備",
			b_rematch = "再戰",
			b_leave_lobby = "離開大廳",
			b_mp_discord = "Balatro 多人模式 Discord 伺服器",
			b_start = "開始",
			b_wait_for_host_start = {
				"等待",
				"房主開始",
			},
			b_wait_for_players = {
				"等待",
				"玩家",
			},
			b_wait_for_guest_ready = {
				"等待",
				"客方準備",
			},
			b_lobby_options = "大廳設定",
			b_copy_clipboard = "複製到剪貼簿",
			b_view_code = "查看代碼",
			b_copy_code = "複製代碼",
			b_leave = "離開",
			b_opts_cb_money = "失去生命時給予補助金",
			b_opts_no_gold_on_loss = "回合失敗時不獲得盲注獎勵",
			b_opts_death_on_loss = "在非 PvP 回合失敗時失去一條命",
			b_opts_start_antes = "起始底注",
			b_opts_diff_seeds = "玩家使用不同種子",
			b_opts_lives = "生命數",

			k_enemy_score = "目前對手分數",
			k_enemy_hands = "對手剩餘手數：",
			k_coming_soon = "即將推出",
			k_wait_enemy = "等待對手完成...",
			k_wait_enemy_reach_this_blind = "等待對手到達此盲注...",
			k_rematch_ready_count = "再戰準備：%s",
			k_rematch_same_seed = "相同種子",
			k_rematch_same_seed_on = "開",
			k_rematch_same_seed_off = "關",
			k_lives = "生命",
			k_lost_life = "失去一條命",
			k_total_lives_lost = "總共失去的生命（每條命 $4）",
			k_attrition_name = "消耗戰",
			k_enter_lobby_code = "輸入大廳密碼",
			k_paste = "從剪貼簿貼上",
			k_username = "使用者名稱：",
			k_enter_username = "輸入使用者名稱",
			k_join_discord = "加入",
			k_discord_msg = "你可以在那裡回報錯誤並找到玩家一起遊玩",
			k_enter_to_save = "按 Enter 儲存",
			k_in_lobby = "在大廳中",
			k_connected = "已連線到服務",
			k_warn_service = "警告：找不到多人連線服務",
			k_set_name = "可在主選單設定名稱（Mods > Multiplayer）",
			k_lobby_options = "大廳設定",
			k_connect_player = "已連線玩家：",
			k_opts_only_host = "只有房主可以更改這些設定",
			k_opts_gm = "模式修改效果",
			k_bl_or = "或",
			k_bl_life = "生",
			k_bl_death = "死",
		},
	},
}
