-- PVP.RLOG: alias to MPAPI's generic replay-log recorder
-- (BalatroMultiplayerAPI/api/replay/recorder.lua, MPAPI.replay).
--
-- The recording/hashing/buffering machinery -- record/begin_run/end_run,
-- the carbon+human dual-stream, card_ref/card_refs -- is mod-agnostic (no
-- PvP-specific knowledge required), so it's owned by MPAPI, the same way
-- MPAPI.playback already owns generic dispatch/timeline for the playback
-- side (api/playback/registry.lua, api/playback/timeline.lua). PVP.RLOG is
-- kept as this alias purely so the many existing PVP.RLOG.record(...) /
-- PVP.RLOG.card_ref(...) call sites throughout this mod (overrides/game.lua,
-- ui/game/timer.lua, compatibility/Preview/CorePreview.lua, etc.) -- the
-- ONLY genuinely PvP-specific part, since only this mod's own game logic
-- knows what a "play"/"buy"/"sell" opcode means -- don't need to change.
--
-- MPAPI fully loads before this mod's core.lua even starts (it's a hard
-- Steamodded dependency, see MultiplayerPvP.json), so MPAPI.replay is
-- guaranteed populated here.
PVP.RLOG = MPAPI.replay
