[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''G.GAME.dollars = G.GAME.dollars + mod'''
position = 'after'
payload = '''
    if PVP and PVP.LOBBY and PVP.LOBBY.code then
        if PVP.GAME.ce_cache == false then
            PVP.GAME.real_money = tonumber(PVP.GAME.real_money) + mod
            if PVP.GAME.real_money ~= G.GAME.dollars then 
                PVP.GAME.ce_cache = true
                Client.send("ce_cache")
            end
            PVP.GAME.real_money = tostring(PVP.GAME.real_money)
        end
    end
'''
match_indent = true
times = 1


[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''self.GAME.dollars = self.GAME.starting_params.dollars'''
position = 'after'
payload = '''
    if PVP and PVP.LOBBY and PVP.LOBBY.code then
        PVP.GAME.real_money = tostring(self.GAME.starting_params.dollars)
    end
'''
match_indent = true
times = 1

